//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dorms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dorms()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public string dorm_id { get; set; }
        public string dorm_name { get; set; }
        public string address { get; set; }
        public Nullable<decimal> spots { get; set; }
        public string phone_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
